

service: lambda-docker-python
frameworkVersion: '2'

provider:
  name: aws
  region: eu-west-1
  stage: prod
  runtime: python3.8
  lambdaHashingVersion: 20201221
  ecr:
    images:
      appimage: ${self:custom.accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/test/docker-lambda:${env:IMAGE_TAG}	

custom: 
  accountId: ${aws:accountId}

functions:
  hello:
    image:
      name: appimage
      command:
        - handler.hello